spring:
  application:
    name: 
      ddau-skekiton
logging:
  level:
    root:
      DEBUG
application:
  database:
    type:
      sqlite
    userName:
      sqlite
    password:
      ddau
    url:
      jdbc:sqlite:ddau.db
    driverClass:
      org.sqlite.JDBC
    dbName:
      ddau
server:
  port:
    8080      
            