## spring 
spring:
  application:
    name: 
      ddau-skekiton

## custom database conf      
application:
  database:
    type:
      sqlite
    userName:
      sqlite
    password:
      ddau
    url:
      jdbc:sqlite:ddau.db
    driverClass:
      org.sqlite.JDBC
    dbName:
      ddau

## server conf      
server:
  port:
    8080  
    
## logging conf    
logging:
#  exception-conversion-word:
#    clr   
  pattern:
#    console:
#      true     
#    dateformat:
#      -yyyy-MM-dd HH:mm:ss.SSS
#    level:
#      -%5p
    file:
      spring-log.log
  file:
    max-history:
      2d
    max-size:
      10M  
  level:
    root:
      DEBUG
    
            